import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import "@copilotkit/react-ui/styles.css"; // Thêm dòng này
import { AgentProvider } from "./provider/AgentContext";
import CopilotKitCustom from "./provider/copilot-provider";
import { getSession } from "@/lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const runtimeUrl = process.env.COPILOTKIT_RUNTIME_URL!;
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CopilotKitCustom
            accessToken={session?.accessToken}
            runtime={runtimeUrl}
          >
            <AgentProvider>{children}</AgentProvider>
          </CopilotKitCustom>
        </ThemeProvider>
      </body>
    </html>
  );
}
